# Generated by Django 3.2.5 on 2021-07-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_data',
            name='age',
            field=models.IntegerField(),
        ),
    ]
