# Generated by Django 3.2.5 on 2022-02-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_alter_db_data_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='db_data',
            name='age',
        ),
        migrations.RemoveField(
            model_name='db_data',
            name='course',
        ),
        migrations.AddField(
            model_name='db_data',
            name='color',
            field=models.CharField(default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='db_data',
            name='href',
            field=models.CharField(default='/', max_length=100),
        ),
        migrations.AddField(
            model_name='db_data',
            name='imageSrc',
            field=models.CharField(default='https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-01.jpg', max_length=200),
        ),
        migrations.AddField(
            model_name='db_data',
            name='price',
            field=models.CharField(default='௹27', max_length=3),
        ),
        migrations.AlterField(
            model_name='db_data',
            name='name',
            field=models.CharField(default='Mutta parota', max_length=20),
        ),
    ]
